// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCxVPgDr6LEtCBrplQiecExVsEf2SXVB7A',
    appId: '1:848387822824:web:3edef33ec90b1aa87b255d',
    messagingSenderId: '848387822824',
    projectId: 'cariintern',
    authDomain: 'cariintern.firebaseapp.com',
    storageBucket: 'cariintern.firebasestorage.app',
    measurementId: 'G-WGFBLLZV35',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBT2A4m-qo9RyoHb4rm-XrOnzpg4F_shgA',
    appId: '1:848387822824:android:dc3e29873cd738627b255d',
    messagingSenderId: '848387822824',
    projectId: 'cariintern',
    storageBucket: 'cariintern.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCptCYLLgIRobRMv_b7vaTqpti1KDJ58OQ',
    appId: '1:848387822824:ios:9977d105961f67247b255d',
    messagingSenderId: '848387822824',
    projectId: 'cariintern',
    storageBucket: 'cariintern.firebasestorage.app',
    iosBundleId: 'com.example.cariintern',
  );
  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCptCYLLgIRobRMv_b7vaTqpti1KDJ58OQ',
    appId: '1:848387822824:ios:9977d105961f67247b255d',
    messagingSenderId: '848387822824',
    projectId: 'cariintern',
    storageBucket: 'cariintern.firebasestorage.app',
    iosBundleId: 'com.example.cariintern',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCxVPgDr6LEtCBrplQiecExVsEf2SXVB7A',
    appId: '1:848387822824:web:5137c2d5477292657b255d',
    messagingSenderId: '848387822824',
    projectId: 'cariintern',
    authDomain: 'cariintern.firebaseapp.com',
    storageBucket: 'cariintern.firebasestorage.app',
    measurementId: 'G-S9DVHQMS82',
  );
}
